"""add_kitchen_model

Revision ID: 05617136c4f7
Revises: a1b2c3d4e5f6
Create Date: 2026-04-15 14:21:21.892541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '05617136c4f7'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kitchen',
    sa.Column('restaurant_id', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kitchen_translation',
    sa.Column('language_code', sa.Enum('FRENCH', 'ENGLISH', 'CHINESE', name='languagecode'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kitchen_id', sa.Integer(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.ForeignKeyConstraint(['kitchen_id'], ['kitchen.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kitchen_user_link',
    sa.Column('kitchen_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['kitchen_id'], ['kitchen.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('kitchen_id', 'user_id')
    )
    # Disable FK enforcement so SQLite batch mode can temporarily copy menu_item
    op.execute("PRAGMA foreign_keys=OFF")
    with op.batch_alter_table('menu_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kitchen_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_menu_item_kitchen_id', 'kitchen', ['kitchen_id'], ['id'], ondelete='SET NULL')
    op.execute("PRAGMA foreign_keys=ON")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("PRAGMA foreign_keys=OFF")
    with op.batch_alter_table('menu_item', schema=None) as batch_op:
        batch_op.drop_constraint('fk_menu_item_kitchen_id', type_='foreignkey')
        batch_op.drop_column('kitchen_id')
    op.execute("PRAGMA foreign_keys=ON")

    op.drop_table('kitchen_user_link')
    op.drop_table('kitchen_translation')
    op.drop_table('kitchen')
    # ### end Alembic commands ###
