"""add unit price to order

Revision ID: 09549a320d43
Revises: fe5f28557e0a
Create Date: 2025-08-26 10:04:47.515582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09549a320d43'
down_revision: Union[str, Sequence[str], None] = 'fe5f28557e0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ordermenuitem', sa.Column('unit_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ordermenuitem', 'unit_price')
    # ### end Alembic commands ###
