"""add active status to menu and category

Revision ID: 0de4f68bd0f9
Revises: 404f0d91f80c
Create Date: 2025-11-10 09:53:07.247849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0de4f68bd0f9'
down_revision: Union[str, Sequence[str], None] = '404f0d91f80c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('active', sa.Boolean()))
    op.add_column('menu', sa.Column('active', sa.Boolean()))
    op.drop_column('menu', 'is_active')
    op.add_column('menu_item', sa.Column('active', sa.Boolean()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu_item', 'active')
    op.add_column('menu', sa.Column('is_active', sa.BOOLEAN(), nullable=False))
    op.drop_column('menu', 'active')
    op.drop_column('category', 'active')
    # ### end Alembic commands ###
