"""add restaurant foreign key to tables

Revision ID: 1f7a559f53ec
Revises: c9f67fcfd2e6
Create Date: 2025-09-19 11:29:32.581262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f7a559f53ec'
down_revision: Union[str, Sequence[str], None] = 'c9f67fcfd2e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurant_table', sa.Column('restaurant_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'restaurant_table', 'restaurant', ['restaurant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'restaurant_table', type_='foreignkey')
    op.drop_column('restaurant_table', 'restaurant_id')
    # ### end Alembic commands ###
