"""add server to order

Revision ID: 1fae30353695
Revises: a914dffe5473
Create Date: 2025-08-05 21:39:50.297368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fae30353695'
down_revision: Union[str, Sequence[str], None] = 'a914dffe5473'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('client_name', sa.Text(), nullable=True))
    op.add_column('order', sa.Column('server_id', sa.Integer(), nullable=True))
    
    # Add foreign key constraint to user table
    op.create_foreign_key(
        'fk_order_server_id',  # constraint name
        'order',               # source table
        'user',                # target table
        ['server_id'],         # source column
        ['id']                 # target column (assuming 'id' is the primary key)
    )
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_order_server_id', 'order', type_='foreignkey')
    op.drop_column('order', 'server_id')
    op.drop_column('order', 'client_name')
    # ### end Alembic commands ###