"""add delete cascade to category

Revision ID: 404f0d91f80c
Revises: a06b83d19ff2
Create Date: 2025-09-22 16:07:03.851715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '404f0d91f80c'
down_revision: Union[str, Sequence[str], None] = 'a06b83d19ff2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categorytranslation', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'categorytranslation', type_='foreignkey')
    op.create_foreign_key(None, 'categorytranslation', 'category', ['category_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'categorytranslation', type_='foreignkey')
    op.create_foreign_key(None, 'categorytranslation', 'category', ['category_id'], ['id'])
    op.alter_column('categorytranslation', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
