"""add favorite table

Revision ID: 5486b3a7d05b
Revises: 5e1fd419160e
Create Date: 2026-05-11 13:12:24.646045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5486b3a7d05b'
down_revision: Union[str, Sequence[str], None] = '5e1fd419160e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'restaurant_id', name='uq_favorite_customer_restaurant')
    )
    op.create_index(op.f('ix_favorite_customer_id'), 'favorite', ['customer_id'], unique=False)
    op.create_index(op.f('ix_favorite_restaurant_id'), 'favorite', ['restaurant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_favorite_restaurant_id'), table_name='favorite')
    op.drop_index(op.f('ix_favorite_customer_id'), table_name='favorite')
    op.drop_table('favorite')
    # ### end Alembic commands ###
