"""remove menu to category

Revision ID: 8d41bcd585a8
Revises: 295ced27eb87
Create Date: 2025-08-19 10:54:38.243560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '8d41bcd585a8'
down_revision: Union[str, Sequence[str], None] = '295ced27eb87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('restaurant_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'category', type_='foreignkey')
    op.create_foreign_key(None, 'category', 'restaurant', ['restaurant_id'], ['id'])
    op.drop_column('category', 'menu_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('menu_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'category', type_='foreignkey')
    op.create_foreign_key(None, 'category', 'menu', ['menu_id'], ['id'])
    op.drop_column('category', 'restaurant_id')
    # ### end Alembic commands ###
