"""add total amount to order

Revision ID: 9ad951c5e2c5
Revises: bd4c85344186
Create Date: 2025-12-03 15:11:04.173174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlmodel import Session, select, text

from app.models.models import Order, OrderMenuItem


# revision identifiers, used by Alembic.
revision: str = '9ad951c5e2c5'
down_revision: Union[str, Sequence[str], None] = 'bd4c85344186'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.add_column('order', sa.Column('total_amount', sa.Integer(), nullable=True))
    # ### end Alembic commands ###
    bind = op.get_bind()
    session = Session(bind=bind)
    
    # Import your models (adjust the import path)
    
    statement = select(Order).where(Order.total_amount == None)
    orders = session.exec(statement).all()
    
    updated_count = 0
    
    for order in orders:
        # Get order items for this order
        items_statement = select(OrderMenuItem).where(OrderMenuItem.order_id == order.id)
        order_items = session.exec(items_statement).all()
        
        # Calculate total
        total = sum(
            item.unit_price * item.quantity 
            for item in order_items 
            if item.unit_price is not None
        )
        
        order.total_amount = total
        session.add(order)
        updated_count += 1
    
    session.commit()
    print(f"✅ Successfully updated {updated_count} orders")

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'total_amount')
    # ### end Alembic commands ###
