"""add category translation

Revision ID: a06b83d19ff2
Revises: 1f7a559f53ec
Create Date: 2025-09-19 17:15:08.969506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a06b83d19ff2'
down_revision: Union[str, Sequence[str], None] = '1f7a559f53ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorytranslation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('language_code', sa.Enum('FRENCH', 'ENGLISH', 'CHINESE', name='languagecode'), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categorytranslation_language_code'), 'categorytranslation', ['language_code'], unique=False)
    op.drop_index(op.f('ix_category_description'), table_name='category')
    op.drop_index(op.f('ix_category_name'), table_name='category')
    op.drop_column('category', 'name')
    op.drop_column('category', 'description')
    op.create_foreign_key(None, 'restaurant_table', 'restaurant', ['restaurant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'restaurant_table', type_='foreignkey')
    op.add_column('category', sa.Column('description', sa.VARCHAR(length=500), nullable=True))
    op.add_column('category', sa.Column('name', sa.VARCHAR(length=50), nullable=False))
    op.create_index(op.f('ix_category_name'), 'category', ['name'], unique=False)
    op.create_index(op.f('ix_category_description'), 'category', ['description'], unique=False)
    op.drop_index(op.f('ix_categorytranslation_language_code'), table_name='categorytranslation')
    op.drop_table('categorytranslation')
    # ### end Alembic commands ###
