"""Added status

Revision ID: a914dffe5473
Revises: b196a8d9a452
Create Date: 2025-08-05 20:45:59.785645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a914dffe5473'
down_revision: Union[str, Sequence[str], None] = 'b196a8d9a452'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('order_status', sa.Enum('CREATED', 'IN_PREPARATION', 'READY', 'SERVED', 'CANCELLED', name='orderstatus'), nullable=False))
    op.add_column('order', sa.Column('payment_status', sa.Enum('UNPAID', 'PAID', 'PREPAID', 'REFUNDED', name='paymentstatus'), nullable=False))
    op.add_column('ordermenuitemlink', sa.Column('quantity', sa.Integer(), nullable=False))
    op.add_column('ordermenuitemlink', sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ordermenuitemlink', 'notes')
    op.drop_column('ordermenuitemlink', 'quantity')
    op.drop_column('order', 'payment_status')
    op.drop_column('order', 'order_status')
    # ### end Alembic commands ###
