"""Add server_id to order

Revision ID: b196a8d9a452
Revises: 8144f3ad608e
Create Date: 2025-07-29 17:02:24.263114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b196a8d9a452'
down_revision: Union[str, Sequence[str], None] = '8144f3ad608e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('server_id', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'server_id')
    # ### end Alembic commands ###