"""add restaurant review table

Revision ID: d903deeaa17e
Revises: 5486b3a7d05b
Create Date: 2026-05-11 13:15:08.268759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd903deeaa17e'
down_revision: Union[str, Sequence[str], None] = '5486b3a7d05b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurant_review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('rating BETWEEN 1 AND 5', name='ck_review_rating_range'),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'restaurant_id', name='uq_review_customer_restaurant')
    )
    op.create_index(op.f('ix_restaurant_review_customer_id'), 'restaurant_review', ['customer_id'], unique=False)
    op.create_index(op.f('ix_restaurant_review_restaurant_id'), 'restaurant_review', ['restaurant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_restaurant_review_restaurant_id'), table_name='restaurant_review')
    op.drop_index(op.f('ix_restaurant_review_customer_id'), table_name='restaurant_review')
    op.drop_table('restaurant_review')
    # ### end Alembic commands ###
