"""add type of restaurant

Revision ID: eb51a83a218c
Revises: 9ad951c5e2c5
Create Date: 2025-12-17 11:57:18.055215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb51a83a218c'
down_revision: Union[str, Sequence[str], None] = '9ad951c5e2c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurant', sa.Column('type', sa.VARCHAR(11), nullable=False, server_default='casual'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurant', 'type')
    # ### end Alembic commands ###
