"""remove menu_item to order and change to order_menu_item

Revision ID: fe5f28557e0a
Revises: fda5d260d354
Create Date: 2025-08-22 17:48:25.666827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe5f28557e0a'
down_revision: Union[str, Sequence[str], None] = 'fda5d260d354'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ordermenuitemlink')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ordermenuitemlink',
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('notes', sa.VARCHAR(), nullable=True),
    sa.Column('order_id', sa.INTEGER(), nullable=False),
    sa.Column('menu_item_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_item.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('order_id', 'menu_item_id')
    )
    # ### end Alembic commands ###
